=== paradiseOffice/sandbox_and_programs/programs/programs/Jotter/cygnet/application.dtd
<!DOCTYPE program [
<!ELEMENT program (meta-information, formats, layout)>
  <!ELEMENT meta-information (app_info, author_info, security, language)>
    <!ELEMENT app_info (name, description, created, modified)>
      <!ELEMENT name (#PCDATA)>
      <!ELEMENT description (#PCDATA)>
      <!ELEMENT created EMPTY>
        <!ATTLIST created date CDATA #REQUIRED>
      <!ELEMENT modified EMPTY>
        <!ATTLIST modified date CDATA #REQUIRED>
    <!ELEMENT author_info (name+,email?, company?)>
      <!ELEMENT name (#PCDATA)>
      <!ELEMENT email (#PCDATA)>
      <!ELEMENT company (#PCDATA)>
    <!ELEMENT security (encryption, keyfile, originating)>
      <!ELEMENT encryption EMPTY>
        <!ATTLIST encryption method (md5|gnupg|cert) #REQUIRED "md5">
      <!ELEMENT keyfile EMPTY>
        <!ATTLIST keyfile link CDATA #REQUIRED>
      <!ELEMENT originating EMPTY>
        <!ATTLIST originating domain CDATA #REQUIRED "http://www.paradise-office.co.uk" >
    <!ELEMENT language EMPTY>
      <!ATTLIST language locale (en-gb | en-us) #REQUIRED "en-gb">
      <!ATTLIST language text (en-gb | en-us) #REQUIRED "en-gb">
      <!ATTLIST language direction (ltr | rtl) #REQUIRED "ltr">
  <!ELEMENT formats (write_open_document_word_files|read_open_document_word_files|write_text_files|read_text_files|write_web_pages|read_web_pages|write_ms_doc_files|read_ms_doc_files|write_open_document_spreadsheets| read_open_document_spreadsheets | write_open_document_presentations | read__open_document_presentations | write_scrolls_xml | read_scrolls_xml | read_ms_excel_files | write_ms_excel_files | read_ms_powerpoint_files | write_ms_powerpoint_files)+ >
    <!ELEMENT write_open_document_word_files EMPTY>
    <!ELEMENT read_open_document_word_files EMPTY>
    <!ELEMENT write_text_files EMPTY>
      <!ATTLIST write_text_files file_ending (linux_or_mac|windows) #REQUIRED "windows">
    <!ELEMENT read_text_files EMPTY>
      <!ATTLIST read_text_files file_ending (linux_or_mac|windows) #REQUIRED "windows">
    <!ELEMENT write_web_pages EMPTY>
      <!ATTLIST write_web_pages type (legacy|modern) #REQUIRED>
    <!ELEMENT read_web_pages EMPTY>
      <!ATTLIST read_web_pages type (legacy|modern) #REQUIRED>
    <!ELEMENT write_ms_doc_files EMPTY>
      <!ATTLIST write_ms_doc_files office-version (1997|2000|2003|2007|2010|2013) #IMPLIED>
    <!ELEMENT read_ms_doc_files EMPTY>
      <!ATTLIST read_ms_doc_files office-version (1997|2000|2003|2007|2010|2013) #IMPLIED>
    <!ELEMENT write_open_document_spreadsheets EMPTY>
    <!ELEMENT read_open_document_spreadsheets EMPTY>
    <!ELEMENT write_open_document_presentations EMPTY>
    <!ELEMENT read_open_document_presentations EMPTY>
    <!ELEMENT write_scrolls_xml EMPTY>
    <!ELEMENT read_scrolls_xml EMPTY>
    <!ELEMENT read_ms_excel_files EMPTY>
      <!ATTLIST read_ms_excel_files office-version (1997|2000|2003|2007|2010|2013) #IMPLIED>
    <!ELEMENT write_ms_excel_files EMPTY>
      <!ATTLIST write_ms_excel_files office-version (1997|2000|2003|2007|2010|2013) #IMPLIED>
    <!ELEMENT read_ms_powerpoint_files EMPTY>
      <!ATTLIST read_ms_powerpoint_files office-version (1997|2000|2003|2007|2010|2013) #IMPLIED>
    <!ELEMENT write_ms_powerpoint_files EMPTY>
      <!ATTLIST write_ms_powerpoint_files office-version (1997|2000|2003|2007|2010|2013) #IMPLIED>
      
  <!ELEMENT layout ((menu_bar, common_bar, file_port, status_bar)|tool_pane)>
    <!ATTLIST layout type (phone|tablet|screen|large_screen) #REQUIRED "screen">
    <!ATTLIST layout effects (none|animation) #REQUIRED "none">
  <!ELEMENT menu_bar (menu)+>
    <!ATTLIST menu_bar no_of_menus CDATA #REQUIRED "1">
    <!ELEMENT menu (menu_item)+>
      <!ATTLIST menu name CDATA #REQUIRED>
      <!ATTLIST menu acckey CDATA #REQUIRED>
      <!ELEMENT menu_item EMPTY>
        <!ATTLIST menu_item name CDATA #REQUIRED>
        <!ATTLIST menu_item acckey CDATA #REQUIRED>
        <!ATTLIST menu_item command (new|open_upload|save_download|save_as_dl|close_file|convert_bfile|                 prepare_statment|log_in|log_out|add_data|query_data|describe_tables|set_up_keys|security_settings|delete_data|update_data|alter_tables|create_tables|create_forms|alter_forms|insert_data_in_forms|create_reports|modify_reports|lexigraphic_checker|ok|cancel) #IMPLIED>
        <!ATTLIST menu_item open_browser (upload_box|download_box|print_box) #IMPLIED>
        <!ATTLIST menu_item opens_dialog CDATA #IMPLIED>
        <!ATTLIST menu_item plugin CDATA #IMPLIED>
        <!ATTLIST menu_item options CDATA #IMPLIED>
        
    <!ELEMENT common_bar (large_icon|control)+>
      <!ELEMENT large_icon EMPTY>
        <!ATTLIST large_icon name CDATA #REQUIRED>
        <!ATTLIST large_icon acckey CDATA #REQUIRED>
        <!ATTLIST large_icon pic CDATA #REQUIRED>
        <!ATTLIST large_icon command (new|open_upload|save_download|save_as_dl|close_file|convert_bfile|                 prepare_statment|log_in|log_out|add_data|query_data|describe_tables|set_up_keys|security_settings|delete_data|update_data|alter_tables|create_tables|create_forms|alter_forms|insert_data_in_forms|create_reports|modify_reports|lexigraphic_checker|ok|cancel) #IMPLIED>
        <!ATTLIST large_icon plugin CDATA #IMPLIED>
        <!ATTLIST large_icon open_browser (upload_box|download_box|print_box) #IMPLIED>
        <!ATTLIST large_icon opens_dialog CDATA #IMPLIED>
        <!ATTLIST large_icon options CDATA #IMPLIED>
        <!ATTLIST large_icon align (left|right|centre) #IMPLIED>
        
      <!ELEMENT control EMPTY (combo_box|spinbox|checkbox_wLabel|radio_btns_wLabel|button|slider|progress_bar|text_field|date_field|time_field|colour_swatches|clipboard_entries_list)+>
        <!ATTLIST control name CDATA #REQUIRED>
        <!ATTLIST control acckey CDATA #REQUIRED>
        <!ATTLIST control spans (1 icon|2 icons|3 icons|4 icons) #REQUIRED>
        <!ELEMENT combo_box EMPTY>
          <!ATTLIST combo_box type (drop down|multi|spinner) #REQUIRED>
          <!ATTLIST combo_box plugin CDATA #IMPLIED>
          <!ATTLIST combo_box pic CDATA #IMPLIED>
          <!ATTLIST combo_box default CDATA #IMPLIED>
        <!ELEMENT spinbox EMPTY>
          <!ATTLIST spinbox default CDATA #IMPLIED>
          <!ATTLIST spinbox step_size CDATA #REQUIRED>
          <!ATTLIST spinbox plugin CDATA #IMPLIED>
          <!ATTLIST spinbox options CDATA #REQUIRED>
        <!ELEMENT checkbox_wLabel EMPTY>
          <!ATTLIST checkbox_wLabel name CDATA #REQUIRED>
          <!ATTLIST checkbox_wLabel plugin CDATA #IMPLIED>
          <!ATTLIST checkbox_wLabel options CDATA #IMPLIED>
        <!ELEMENT radio_btns_wLabel EMPTY>
          <!ATTLIST radio_btns_wLabel name CDATA #REQUIRED>
          <!ATTLIST radio_btns_wLabel plugin CDATA #IMPLIED>
          <!ATTLIST radio_btns_wLabel options CDATA #IMPLIED>
          <!ATTLIST radio_btns_wLabel group CDATA #REQUIRED>
        <!ELEMENT button EMPTY>
          <!ATTLIST button name CDATA #REQUIRED>
          <!ATTLIST button command (new|open_upload|save_download|save_as_dl|close_file|convert_bfile|                 prepare_statment|log_in|log_out|add_data|query_data|describe_tables|set_up_keys|security_settings|delete_data|update_data|alter_tables|create_tables|create_forms|alter_forms|insert_data_in_forms|create_reports|modify_reports|lexigraphic_checker|ok|cancel) #IMPLIED>
          <!ATTLIST button plugin CDATA #IMPLIED>
          <!ATTLIST button options CDATA #IMPLIED>
          <!ATTLIST button (left|right|centre) #IMPLIED>
        <!ELEMENT slider EMPTY>
          <!ATTLIST slider min CDATA #REQUIRED>
          <!ATTLIST slider max CDATA #REQUIRED>
          <!ATTLIST slider default CDATA #IMPLIED>
          <!ATTLIST slider plugin CDATA #IMPLIED>
          <!ATTLIST slider options CDATA #IMPLIED>
        <!ELEMENT progress_bar EMPTY>
          <!ATTLIST progress_bar min CDATA #REQUIRED>
          <!ATTLIST progress_bar max CDATA #REQUIRED>
          <!ATTLIST progress_bar default CDATA #IMPLIED>
          <!ATTLIST progress_bar plugin CDATA #IMPLIED>
          <!ATTLIST progress_bar options CDATA #IMPLIED>
          <!ATTLIST progress_bar type (vertical|horizontal) #REQUIRED "horizontal" >
        <!ELEMENT text_field EMPTY>
          <!ATTLIST text_field name CDATA #REQUIRED>
          <!ATTLIST text_field spans (10 chars|25 chars|50 chars|100 chars) "50 chars">
          <!ATTLIST text_field plugin CDATA #REQUIRED>
          <!ATTLIST text_field options CDATA #REQUIRED>
          <!ATTLIST text_field valid (credit_card_num|custom_card|email_address|national_insurance|post_code|zip_code|short_text|uk_mobile_num|uk_phone_num|us_mobile_num|us_phone_num|web_address) "short_text">
        <!ELEMENT date_field EMPTY>
          <!ATTLIST date_field name CDATA #REQUIRED>
          <!ATTLIST date_field min CDATA #IMPLIED>
          <!ATTLIST date_field max CDATA #IMPLIED>
          <!ATTLIST date_field plugin CDATA #REQUIRED>
          <!ATTLIST date_field options CDATA #REQUIRED>
        <!ELEMENT time_field EMPTY>
          <!ATTLIST time_field name CDATA #REQUIRED>
          <!ATTLIST time_field min CDATA #IMPLIED>
          <!ATTLIST time_field max CDATA #IMPLIED>
          <!ATTLIST time_field plugin CDATA #REQUIRED>
          <!ATTLIST time_field options CDATA #REQUIRED>
        <!ELEMENT colour_swatches EMPTY>
          <!ATTLIST colour_swatches name CDATA #REQUIRED>
          <!ATTLIST colour_swatches plugin CDATA #REQUIRED>
          <!ATTLIST colour_swatches options CDATA #IMPLIED>
          <!ATTLIST colour_swatches max_colours CDATA "12">
        <!ELEMENT clipboard_entries_list EMPTY>
          <!ATTLIST clipboard_entries_list command CDATA #FIXED "clipboard_words">
          <!ATTLIST clipboard_entries_list name CDATA #REQUIRED>
          
      <!ELEMENT tool_pane (tool_box)+>
        <!ELEMENT tool_box (control|icon)+>
          <!ATTLIST tool_box name CDATA #REQUIRED>
         <!ELEMENT control EMPTY (combo_box|spinbox|checkbox_wLabel|radio_btns_wLabel|button|slider|progress_bar|text_field|date_field|time_field|colour_swatches|clipboard_entries_list)+>
        <!ATTLIST control name CDATA #REQUIRED>
        <!ATTLIST control spans (1 icon|2 icons|3 icons|4 icons) #REQUIRED>
        <!ELEMENT combo_box EMPTY>
          <!ATTLIST combo_box type (drop down|multi|spinner) #REQUIRED>
          <!ATTLIST combo_box plugin CDATA #IMPLIED>
          <!ATTLIST combo_box pic CDATA #IMPLIED>
          <!ATTLIST combo_box default CDATA #IMPLIED>
        <!ELEMENT spinbox EMPTY>
          <!ATTLIST spinbox default CDATA #IMPLIED>
          <!ATTLIST spinbox step_size CDATA #REQUIRED>
          <!ATTLIST spinbox plugin CDATA #IMPLIED>
          <!ATTLIST spinbox options CDATA #REQUIRED>
        <!ELEMENT checkbox_wLabel EMPTY>
          <!ATTLIST checkbox_wLabel name CDATA #REQUIRED>
          <!ATTLIST checkbox_wLabel plugin CDATA #IMPLIED>
          <!ATTLIST checkbox_wLabel options CDATA #IMPLIED>
        <!ELEMENT radio_btns_wLabel EMPTY>
          <!ATTLIST radio_btns_wLabel name CDATA #REQUIRED>
          <!ATTLIST radio_btns_wLabel plugin CDATA #IMPLIED>
          <!ATTLIST radio_btns_wLabel options CDATA #IMPLIED>
          <!ATTLIST radio_btns_wLabel group CDATA #REQUIRED>
        <!ELEMENT button EMPTY>
          <!ATTLIST button name CDATA #REQUIRED>
          <!ATTLIST button command (new|open_upload|save_download|save_as_dl|close_file|convert_bfile|                 prepare_statment|log_in|log_out|add_data|query_data|describe_tables|set_up_keys|security_settings|delete_data|update_data|alter_tables|create_tables|create_forms|alter_forms|insert_data_in_forms|create_reports|modify_reports|lexigraphic_checker|ok|cancel) #IMPLIED>
          <!ATTLIST button plugin CDATA #IMPLIED>
          <!ATTLIST button options CDATA #IMPLIED>
        <!ELEMENT slider EMPTY>
          <!ATTLIST slider min CDATA #REQUIRED>
          <!ATTLIST slider max CDATA #REQUIRED>
          <!ATTLIST slider default CDATA #IMPLIED>
          <!ATTLIST slider plugin CDATA #IMPLIED>
          <!ATTLIST slider options CDATA #IMPLIED>
        <!ELEMENT progress_bar EMPTY>
          <!ATTLIST progress_bar min CDATA #REQUIRED>
          <!ATTLIST progress_bar max CDATA #REQUIRED>
          <!ATTLIST progress_bar default CDATA #IMPLIED>
          <!ATTLIST progress_bar plugin CDATA #IMPLIED>
          <!ATTLIST progress_bar options CDATA #IMPLIED>
          <!ATTLIST progress_bar type (vertical|horizontal) #REQUIRED "horizontal" >
        <!ELEMENT text_field EMPTY>
          <!ATTLIST text_field name CDATA #REQUIRED>
          <!ATTLIST text_field spans (10 chars|25 chars|50 chars|100 chars) "50 chars">
          <!ATTLIST text_field plugin CDATA #REQUIRED>
          <!ATTLIST text_field options CDATA #REQUIRED>
        <!ELEMENT date_field EMPTY>
          <!ATTLIST date_field name CDATA #REQUIRED>
          <!ATTLIST date_field min CDATA #IMPLIED>
          <!ATTLIST date_field max CDATA #IMPLIED>
          <!ATTLIST date_field plugin CDATA #REQUIRED>
          <!ATTLIST date_field options CDATA #REQUIRED>
        <!ELEMENT time_field EMPTY>
          <!ATTLIST time_field name CDATA #REQUIRED>
          <!ATTLIST time_field min CDATA #IMPLIED>
          <!ATTLIST time_field max CDATA #IMPLIED>
          <!ATTLIST time_field plugin CDATA #REQUIRED>
          <!ATTLIST time_field options CDATA #REQUIRED>
        <!ELEMENT colour_swatches EMPTY>
          <!ATTLIST colour_swatches name CDATA #REQUIRED>
          <!ATTLIST colour_swatches plugin CDATA #REQUIRED>
          <!ATTLIST colour_swatches options CDATA #IMPLIED>
          <!ATTLIST colour_swatches max_colours CDATA "12">
        <!ELEMENT clipboard_entries_list EMPTY>
          <!ATTLIST clipboard_entries_list command CDATA #FIXED "clipboard_words">
          <!ATTLIST clipboard_entries_list name CDATA #REQUIRED>
          
      <!ELEMENT icon EMPTY>
        <!ATTLIST icon name CDATA #REQUIRED>
        <!ATTLIST icon acckey CDATA #IMPLIED>
        <!ATTLIST icon pic CDATA #REQUIRED>
        <!ATTLIST icon plugin CDATA #REQUIRED>
        <!ATTLIST icon options CDATA #IMPLIED>
    <!ELEMENT file_port (context_menu*,lexigraphic_checker)>
      <!ATTLIST file_port type (page|calendar|tabular) #REQUIRED>
      <!ELEMENT context_menu (menu,(menu_item)+)>
        <!ELEMENT menu (menu_item)+>
          <!ATTLIST menu name CDATA #REQUIRED>
          <!ATTLIST menu acckey CDATA #REQUIRED>
          <!ELEMENT menu_item EMPTY>
            <!ATTLIST menu_item name CDATA #REQUIRED>
            <!ATTLIST menu_item acckey CDATA #REQUIRED>
            <!ATTLIST menu_item command (new|open_upload|save_download|save_as_dl|close_file|convert_bfile|                 prepare_statment|log_in|log_out|add_data|query_data|describe_tables|set_up_keys|security_settings|delete_data|update_data|alter_tables|create_tables|create_forms|alter_forms|insert_data_in_forms|create_reports|modify_reports|lexigraphic_checker|ok|cancel) #IMPLIED>
            <!ATTLIST menu_item open_browser (upload_box|download_box|print_box) #IMPLIED>
            <!ATTLIST menu_item opens_dialog CDATA #IMPLIED>
            <!ATTLIST menu_item plugin CDATA #IMPLIED>
            <!ATTLIST menu_item options CDATA #IMPLIED>
            <!ATTLIST menu_item pic CDATA #REQUIRED>
    <!ELEMENT lexigraphic_checker EMPTY>
      <!ATTLIST lexigraphic_checker mode (autocheck_both|grammar_on|spelling_on) #REQUIRED>
    <!ELEMENT status_bar (label)*>
      <!ELEMENT label EMPTY>
      <!ATTLIST label command CDATA #FIXED "update_status_msgs">
      <!ATTLIST label update (1 min|5 min|30 min| 1 hour) #REQUIRED "1 min">
      <!ATTLIST label name CDATA #REQUIRED>
      <!ATTLIST label plugin CDATA #REQUIRED>
      <!ATTLIST label options CDATA #IMPLIED>
      
]>

=== paradiseOffice/sandbox_and_programs/programs/Jotter/Jotter/cygnet/main_app.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE program PUBLIC "-//paradise-office//DTD cygnet-application 0.1//EN" "http://www.linux-paradise.co.uk/DTDs/cygnet/application.dtd">
  <program>
    <meta-information>
      <app_info>
          <name>Jotter</name>
          <description>Edit up to 20 text documents at a time. Can be used for any text files or programming. </description>
          <created date="20131205" />
          <modified date="20131205" />
      </app_info>
      <author_info>
          <name>Hazel Windle</name>
          <email>lead-dev@linux-paradise.co.uk</email>
          <company>Paradise Office</company>
      </author_info>
      <security>
          <encryption method="md5" />
          <keyfile link="check_20131205.md5" />
          <originating domain="http://www.paradise-office.co.uk" />
      </security>
      <language locale="en-gb" text="en-gb" direction="ltr" />
    </meta-information>
    
    <formats>
      <write_text_files file_ending="linux_or_mac" />
      <read_text_files file_ending="linux_or_mac" />
    </formats>
    
    <layout type="simple_screen" effects="animation">
    
      <menu_bar no_of_menus="5">
        <menu name="File" acckey="F">
          <menu_item name="New File" acckey="Ctrl + N" command="new" />
          <menu_item name="Open" acckey="Ctrl + O" command="open_upload" open_browser="upload_box" />
          <menu_item name="Save" acckey="Ctrl + S" command="save_download" open_browser="download_box" />
          <menu_item name="Save As" acckey="Ctrl + Shift + A" command="save_as_dl" opens_dialog="dialog_saveas.xml" />
          <menu_item name="Save All" acckey="Ctrl + L" plugin="save_all" />
          <menu_item name="Print Preview" acckey="Alt + P" command="print_view" opens_dialog="dialog_print_preview.xml" />
          <menu_item name="Print File" acckey="Ctrl + P" plugin="print" open_browser="print_box" />
          <menu_item name="Close File" acckey="Ctrl + W" command="close_file" opens_dialog="dialog_confirm.xml" />
        </menu>
        <menu name="Edit" acckey="E">
          <menu_item name="Undo" acckey="Ctrl + Z" command="undo" />
          <menu_item name="Redo" acckey="Ctrl + R" command="redo" />
          <menu_item name="Undo History" acckey="Shift + Ctrl + Z" command="undo_history" />
          <separator />
          <menu_item name="Cut" acckey="Ctrl + X" plugin="cut_words" />
          <menu_item name="Copy" acckey="Ctrl + C" plugin="copy_words" />
          <menu_item name="Paste" acckey="Ctrl + V" plugin="paste_words" />
          <menu_item name="Clipboard" acckey="Ctrl Shift + V" plugin="clipboard_words" opens_dialog="dialog_clipboard.xml" />
          <separator />
          <menu_item name="Insert Character" plugin="insert_char" opens_dialog="dialog_insert_char.xml" />
          <menu_item name="UPPER CASE" acckey="Ctrl + U" plugin="text_case" options="upper" />
          <menu_item name="lower case" acckey="Shift + Ctrl + U" plugin="text_case" options="lower" />
          <menu_item name="Title Case" acckey="Ctrl + T" plugin="text_case" options="title" />
          <menu_item name="Find and Replace" acckey="Ctrl + F" plugin="find_and_replace" opens_dialog="dialog_find_and_replace.xml" />
        </menu>
        <menu name="Bookmarks" acckey="B">
            <menu_item name="Add Bookmark" acckey="Shift + Ctrl + B" plugin="add_bookmark" opens_dialog="dialog_bookmark_name.xml"  />
            <separator />
            <menu_item name="Line 1: First Line" plugin="bookmark" option="First Line" />
        </menu>
        <menu name="Options" acckey="O">
            <menu_item name="Change Font" plugin="change_font" opens_dialog="dialog_change_font.xml" />
            <menu_item name="Set Tab Width" plugin="set_tab_width" opens_dialog="dialog_set_tab_width.xml" />
            <menu_item name="CSV Fields" plugin="csv_fields" opens_dialog="dialog_csv_fields.xml" />
            <menu_item name="Highlighting" plugin="syntax_highlighter" opens_dialog="dialog_syntax_highlighter.xml" />
            <menu_item name="Spellcheck" acckey="F7" plugin="spellcheck" opens_dialog="dialog_spellcheck.xml" />
            <menu_item name="Sort" plugin="sort_text" opens_dialog="dialog_sort.xml" />
        </menu>
        <menu name="Help" acckey="H">
            <menu_item name="Help Contents" command="help" acckey="F1" />
        </menu>
        
   </layout>
 </program>

=== paradiseOffice/sandbox_and_programs/paradise_office_site/sandbox_v1.0/cygnet_maker/cy_tests/simple_word_processor/main_app.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE program PUBLIC "-//paradise-office//DTD cygnet-application 0.1//EN" "http://www.linux-paradise.co.uk/DTDs/cygnet/application.dtd">
  <program>
    <meta-information>
      <app_info>
        <name>Simple Word Processor</name>
        <description>Edit and create short texts.</description>
        <created date="20130724" />
        <modified date="20130816" />
      </app_info>
      <author_info> 
        <name>Hazel Windle</name>
        <email>lead-dev@linux-paradise.co.uk</email>
        <company>Paradise Software</company>
      </author_info>
      <security> 
        <encryption method="md5" />
        <keyfile link="check20130816.md5" />
        <originating domain="http://www.paradise-office.co.uk" />
      </security>
      <language locale="en-gb" text="en-gb" direction="ltr" />
    </meta-information>

    <formats>
      <write_open_document_word_files />
      <read_open_document_word_files />
      <write_text_files file_ending="linux_or_mac" />
      <read_text_files file_ending="linux_or_mac" />
      <write_web_pages type="legacy" />
      <read_web_pages type="modern" />
      <write_ms_doc_files office-version="1997" />
      <read_ms_doc_files office-version="1997" />
    </formats>

    <layout type="tablet" effects="animation">
      <menu_bar no_of_menus="5">

        <menu name="File" acckey="F">
	  <menu_item name="New File" acckey="Ctrl + N" command="new" />
	  <menu_item name="Open" acckey="Ctrl + O" command="open_upload" open_browser="upload_box" />
	  <menu_item name="Save" acckey="Ctrl + S" command="save_download" open_browser="download_box" />
	  <menu_item name="Save As" acckey="Ctrl Shift + A" command="save_as_dl" opens_dialog="dialog_saveas.xml" />
	  <menu_item name="Convert File" acckey="Alt + V" command="convert_bfile" opens_dialog="dialog_convert.xml" />
	  <menu_item name="Print Preview" acckey="Alt + P" command="print_view" opens_dialog="dialog_print_preview.xml" />
	  <menu_item name="Print File" acckey="Ctrl + P" plugin="print" open_browser="print_box" />
	  <menu_item name="Close File" acckey="Ctrl + W" command="close_file" opens_dialog="dialog_confirm.xml" />
        </menu>
        <menu name="Edit" acckey="E">
          <menu_item name="Cut" acckey="Ctrl + X" plugin="cut_words" />
          <menu_item name="Copy" acckey="Ctrl + C" plugin="copy_words" />
	  <menu_item name="Paste" acckey="Ctrl + V" plugin="paste_words" />
	  <menu_item name="Clipboard" acckey="Ctrl Shift + V" plugin="clipboard_words" opens_dialog="dialog_clipboard.xml" />
	  <menu_item name="Delete" acckey="Del" plugin="del_words" />
	</menu>
	<menu name="View" acckey="V">
	  <menu_item name="10% Zoom" acckey="-10" plugin="zoom_up_page" options="10" />
	  <menu_item name="25% Zoom" acckey="-25" plugin="zoom_up_page" options="25" />
	  <menu_item name="50% Zoom" acckey="-50" plugin="zoom_up_page" options="50" />
	  <menu_item name="100% Zoom" acckey="0" plugin="zoom_up_page" options="100" />
	  <menu_item name="125% Zoom" acckey="+25" plugin="zoom_up_page" options="125" />
	  <menu_item name="150% Zoom" acckey="+50" plugin="zoom_up_page" options="150" />
	  <menu_item name="Fit Page Width" acckey="W" plugin="zoom_up_page" options="fitWidth" />
	  <menu_item name="Fit Page Height" acckey="H" plugin="zoom_up_page" options="fitHeight" />
	</menu>
	<menu name="Insert" acckey="I">
	  <menu_item name="Break" acckey="B" plugin="text_breaks" opens_dialog="dialog_breaks.xml" />
	  <menu_item name="Special Character" acckey="S" plugin="spec_char" opens_dialog="dialog_spec_char.xml" />
	  <menu_item name="Picture" acckey="P" command="pic_preview" opens_dialog="dialog_imgadd.xml" />
	  <menu_item name="Table" acckey="T" plugin="insert_table" opens_dialog="dialog_tableadd.xml" />
	  <menu_item name="Reference" acckey="R" plugin="insert_ref" opens_dialog="dialog_refadd.xml" />
	  <menu_item name="Link" acckey="L" plugin="insert_link" opens_dialog="dialog_linkadd.xml" />
	  <menu_item name="Text File" acckey="E" plugin="insert_text" opens_dialog="dialog_textadd.xml" />
	</menu>
	<menu name="Format" acckey="F">
	  <menu_item name="Words" acckey="W" plugin="format_words" opens_dialog="dialog_format_words.xml" />
	  <menu_item name="Paragraph" acckey="P" plugin="format_para" opens_dialog="dialog_format_para.xml" />
	  <menu_item name="Text Frame" acckey="T" plugin="format_frame" opens_dialog="dialog_format_frame.xml" />
	  <menu_item name="Style Table" acckey="a" plugin="format_table" opens_dialog="dialog_format_table.xml" />
	  <menu_item name="Picture" acckey="I" plugin="format_pic" opens_dialog="dialog_format_pic.xml" />
	  <menu_item name="Page" acckey="G" plugin="format_pages" opens_dialog="dialog_format_pages.xml" />
	</menu>
	<menu name="Help" acckey="H">
	  <menu_item name="About" acckey="A" plugin="show_about" opens_dialog="dialog_about.xml" />
	</menu>
      </menu_bar>

      <common_bar>
	<large_icon name="Print" acckey="Win + P" pic="icons/common/document-print.png" plugin="print" open_browser="print_box" />
	<large_icon name="Time" acckey="Win + T" pic="icons/common/time.png" plugin="current_time" options="now" />
	<large_icon name="Wikipedia" acckey="Win + W" pic="icons/text/book.png" plugin="research_wiki" opens_dialog="dialog_wiki_research_pane.xml" />
	<control name="Dictionary" acckey="Win + D" spans="large_icon">
	  <text_field name="Enter word" opens_dialog="dialog_lookup.xml" />
	  <button name="Look Up" pic="icons/internet/search.png" />
	</control>
	<large_icon name="Grammar" acckey="Win + G" pic="icons/text/grammar.png" command="lexigraphic_checker" opens_dialog="dialog_grammar.xml" />
      </common_bar>
      
      <tool_pane>
	<tool_box name="Words">
	  <control name="font_picker" spans="3 icons">
	    <combo_box type="drop down" plugin="font_list" />
	  </control>
	  <control name="font_size" spans="1 icon">
	    <spinbox default="12" step_size="1" plugin="format_words" options="font_size" />
	  </control>
	  <icon name="bold" acckey="Ctrl + B" pic="icons/text/format-text-bold.png" plugin="format_words" options="bold" />
	  <icon name="underline" acckey="Ctrl + U" pic="icons/text/format-text-underline.\
png" plugin="format_words" options="underline" />
	  <icon name="italic" acckey="Ctrl + I" pic="icons/text/format-text-italic.png" plugin="format_words" options="italic" />
	  <icon name="all caps" acckey="Ctrl Shift + U" pic="icons/text/pencil.png" plugin="all_caps" />
	  <control name="Text colour" spans="1 icon">
      <combo_box type="drop down" plugin="format_words" options="text_colour" />
	  </control>
	  <control name="Highlight colour" spans="1 icon">
      <combo_box type="drop down" plugin="format_words" options="highlight_colour" />
	  </control>
    <icon name="Superscript" pic="icons/text/superscript.png" plugin="format_words" options="sup_script" />
    <icon name="Subscript" pic="icons/text/subscript.png" plugin="format_words"  options="sub_script" />
	  <control name="Styles" spans="3 icons">
	    <combo_box type="drop down" plugin="styles_list" />
	  </control>
	  <icon name="add style" pic="icons/text/styles.png" plugin="add_style" />
	</tool_box>
	<tool_box name="paragraph">
	  <icon name="Left" acckey="Ctrl + L" pic="icons/text/format-justify-left.png'" plugin="justify" options="left" />
	  <icon name="Centre" pic="icons/text/format-justify-center.\
png" plugin="justify" options="centre" />
	  <icon name="Right" acckey="Ctrl + R" pic="icons/text/format-justify-right.png" plugin="justify" options="right" />
	  <icon name="Justify" acckey="Ctrl + J" pic="icons/text/format-justify-fill.p\
ng" plugin="justify" options="justify" />
	  <icon name="first line indent" pic="icons/text/sticky-notes\
.png" plugin="1st_line_indent" />
	  <icon name="Drop cap" pic="icons/text/drop_cap.png" plugin="drop_cap" />
	  <icon name="Increase Indent" pic="icons/text/format-indent-more.png" plugin="indent" options="increase" />
	  <icon name="Decrease Indent" pic="icons/text/format-indent-less.png" plugin="indent" options="decrease" />
	  <control name="line height" spans="2 icons">
	    <spinbox default="1" step_size="0.5" plugin="line_height" /><label name="line" />
	  </control>
	  <control name="left tab stop" spans="2 icons">
	    <spinbox default="0" step_size="0.5" plugin="set_tabs"  options="left_cm" /><label name="cm" />
	  </control>
	</tool_box>
	<help_box></help_box>
      </tool_pane>
      <file_port type="page">
	<context_menu />
	<lexigraphic_checker mode="autocheck_both" />
      </file_port>
      <status_bar>
	<label name="Word count" update="1 min" plugin="word_count" />
      </status_bar>
    </layout>
  </program>
